export enum Category {
  Business = 'business',
  Entertainment = 'entertainment',
  General = 'general',
  Health = 'health',
  Science = 'science',
  Sports = 'sports',
  Technology = 'technology',
}

export enum Language {
  Arabic = 'ar',
  German = 'de',
  English = 'en',
  Spanish = 'es',
  French = 'fr',
  Hebrew = 'he',
  Italian = 'it',
  Dutch = 'nl',
  Norwegian = 'no',
  Portuguese = 'pt',
  Russian = 'ru',
  Swedish = 'sv',
  Chinese = 'zh',
}

export enum Country {
  UAE = 'ae',
  Argentina = 'ar',
  Austria = 'at',
  Australia = 'au',
  Belgium = 'be',
  Bulgaria = 'bg',
  Brazil = 'br',
  Canada = 'ca',
  Switzerland = 'ch',
  China = 'cn',
  Colombia = 'co',
  Cuba = 'cu',
  CzechRepublic = 'cz',
  Germany = 'de',
  Egypt = 'eg',
  France = 'fr',
  UnitedKingdom = 'gb',
  Greece = 'gr',
  HongKong = 'hk',
  Hungary = 'hu',
  Indonesia = 'id',
  Ireland = 'ie',
  Israel = 'il',
  India = 'in',
  Italy = 'it',
  Japan = 'jp',
  SouthKorea = 'kr',
  Lithuania = 'lt',
  Latvia = 'lv',
  Morocco = 'ma',
  Mexico = 'mx',
  Malaysia = 'my',
  Nigeria = 'ng',
  Netherlands = 'nl',
  Norway = 'no',
  NewZealand = 'nz',
  Philippines = 'ph',
  Poland = 'pl',
  Portugal = 'pt',
  Romania = 'ro',
  Serbia = 'rs',
  Russia = 'ru',
  SaudiArabia = 'sa',
  Sweden = 'se',
  Singapore = 'sg',
  Slovenia = 'si',
  Slovakia = 'sk',
  Thailand = 'th',
  Turkey = 'tr',
  Taiwan = 'tw',
  Ukraine = 'ua',
  UnitedStates = 'us',
  Venezuela = 've',
  SouthAfrica = 'za',
}
